# Generated by Django 4.1.3 on 2022-11-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.CharField(max_length=30),
        ),
    ]
