# Generated by Django 4.1.3 on 2022-11-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_book_publish_date_book_publish_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.CharField(default='good', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.PositiveIntegerField(),
        ),
    ]
