# Generated by Django 4.1.3 on 2022-11-05 07:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book_comments_alter_book_publish_year'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('books_by_author', django.db.models.manager.Manager()),
            ],
        ),
    ]
